apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "..fullname" . }}-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["pods","pods/log", "deployments", "jobs"]
  verbs: ["get", "watch", "list","create","update","delete","edit"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "..fullname" . }}-role-binding
  namespace: {{ .Values.deployment.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "..fullname" . }}
  namespace: {{ .Values.backend.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "..fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "..fullname" . }}-role-binding
  namespace: {{ .Values.finetune.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "..fullname" . }}
  namespace: {{ .Values.backend.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "..fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io