apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  labels:
    {{- include "..labels" . | nindent 4 }}
    {{- include "..selectorLabels" . | nindent 4 }}
type: Opaque
data:
  .env: {{ .Files.Get .Values.secretEnv.backendSecretPath | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-inference-secret
  labels:
    {{- include "..labels" . | nindent 4 }}
    {{- include "..selectorLabels" . | nindent 4 }}
type: Opaque
data:
  .env: {{ .Files.Get .Values.secretEnv.inferenceSecretPath | b64enc }}