apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-backend-svc
  namespace: {{ .Values.backend.namespace }}
  labels:
    {{- include "..labels" . | nindent 4 }}
    {{- include "..backendSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "..backendSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-inference-svc
  namespace: {{ .Values.inference.namespace }}
  labels:
    {{- include "..labels" . | nindent 4 }}
    {{- include "..inferenceSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.inference.service.type }}
  ports:
    - port: {{ .Values.inference.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "..inferenceSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-frontend-svc
  namespace: {{ .Values.frontend.namespace }}
  labels:
    {{- include "..labels" . | nindent 4 }}
    {{- include "..frontendSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "..frontendSelectorLabels" . | nindent 4 }}
